apiVersion: v1
kind: Secret
metadata:
  name: kltn-app-secrets
  namespace: dev
type: Opaque
stringData:
  JWT_SECRET: replace-me
  MONGO_ATLAS_URI: replace-me
  MONGO_URL: replace-me
  TOGETHER_API_KEY: replace-me